### ISSUE TITLE
想问一下Cmake的版本

### ISSUE THREAD

**Issue by liziyuanyuan** [SuRuiMeng/offScreen#2]
大佬，想问一下你Cmake的版本，我整了半天老错。感谢您。

**Comment by Sruimeng** [comment]
Xvfb :5 -screen 0 800x600x24 & export DISPLAY=:5 最重要的是这行命令和安装xvfb 剩下的你能把图形程序跑起来就行，cmake只是跨平台方便点，这个项目里其他代码都不重要

**Comment by liziyuanyuan** [comment]
刚整明白，想关闭issue就看见回复啦，感谢!
